.editorconfig, .gitattributes, .gitignore, v.mod
Reasons:
- generate service files for git/GitHub to have an excellent maintained repo and suitable "languages" on the GitHub page
- create a mod file
=> Generate service files (fix #24)

c2v.v
I have clang 14, I would like to stop having to manually add this version to my local copy of c2v.
=> Add clang v14 to lookup versions list

c2v.v, tests/7.api_types.out
```c
typedef struct tm_clock_o
{
uint64_t opaque;
} tm_clock_o;
```
old:
```v
struct Tm_clock_o {
opaque i64
}
```
new:
```v
struct Tm_clock_o {
opaque u64
}
```
=> fix bug that uint64_t will be converted to i64

.gitignore, c2v.v, tests/6.types.c, tests/6.types.out
This is a small fix to avoid capitalization u16, usize, isize, f32, bool and voidptr.
I also added `C.intptr_t` to the types test, but I don't see how this is supposed to work.
=> fix capitalization for u16 and friends

src/builtins.v
Seems builtins.v is just a hollow file and contains no logic at all. All builtins logic was placed in the c2v.v file
=> Remove `builtins.v`

src/c2v.v
This PR adds these two functions.
[fseek](https://man7.org/linux/man-pages/man3/fseek.3.html)
[rewind](https://man7.org/linux/man-pages/man3/rewind.3p.html)
=> Add fseek and rewind built-in functions

.github/workflows/ci.yml
Trigger push jobs only on push to main branch, not in PR (this provides to double run for the same jobs)
=> Improve CI push trigger

src/c2v.v, tests/13.switch.c, tests/13.switch.out
Fix wrong code for switch stmt
```c
const int a = 0;
void f() 
{ 
switch(a)
{
default:
break;
case 0:
break;
}
}
``` 
```
C to V translator 0.3.1
translating tests/0.switch.c ... tests/0.switch.v:11:2: error: invalid expression: unexpected token `}`
9 | fn f()  {
10 |     match a {
11 |     }
|     ^
12 |      else {
13 |
```
=> fix switch with default stmt before case stmt

src/c2v.v, tests/15.multi_var_decl.c, tests/15.multi_var_decl.out
Fix var declaration ([V Issue  #17670](https://github.com/vlang/v/issues/17670))
```C
int main() {
int n, r, sum = 0, temp;
}
```
```V
[translated]
module main
fn main() {
n := 0
r := 0
sum := 0
temp := 0
}
```
=> fix code generated to multiple var declaration

README.md, src/c2v.v, tests/run_tests.vsh, tests/test.c/1.hello.c, tests/test.c/1.hello.out
put doom hack under doom define, to use run with -d doom
related to error https://github.com/vlang/c2v/issues/124 but not a total fix this just fixes so a wrapper can be created.
May break doom tests but not when the new define is set.
=> fix issue with .c in folder name

.github/workflows/doom_gfx_regressions.yml
Set `VTMP` env var to let `vgret` output any fail images to a predictable path.
It is already done so in V's CI https://github.com/vlang/v/blob/13fd5493d34b45751a31ea0ff5119a1e064310c5/.github/workflows/gg_regressions_ci.yml#L20
=> ci: set a predictable temp output path for `vgret` with `VTMP`

src/c2v.v, tests/run_tests.vsh
Before this PR, the module name was generated wrongly when generating a module for a single file, when the path to this file was relative
=> Fix module name when generating wrapper

tests/run_tests.vsh
Simplifies the script and improves platform independence. c2v currently produces different outcome on windows, so the script will still fail on windows. But in general this improvement creates the base for windows compatibility.
- Uses consts for c2v and test path instead of passing them as args to simplify the logic.
- eprint instead of prints for error output
- join_path to join file paths
=> test: update `run_test.vsh`

src/c2v.v
=> fix missing `as` as keyword

src/c2v.v
Fix missing param name when generating C function with body on wrapper mode.
=> fix missing param name + @[c2v_variadic] attr

src/c2v.v
This PR fixes some minor issues spotted translating TCC source.
- `case` label without space
- missing braces on `case`
- missing escape char `\r`, `\v`, `\t`, `\f` handling
- sizeof*var to sizeof(*var)
- add `fn` to keyword
- add `__FUNCTION__` predefined
- `[export]` to `@[export]`
- `s....field` to `s.field`
=> some minor fixes 

.github/workflows/ci.yml, .gitignore, src/c2v.v, src/node.v, tests/22.getline_macos.out, tests/5.struct.out
Had to fix `tests/5.struct.out` due to recent changes in `v fmt`.
Fixed https://github.com/vlang/v/issues/22116
=> fix var/const conflict, update format of test output, update json ignore

src/node.v, src/struct.v, tests/24.typedef_struct.h, tests/24.typedef_struct.out, tests/24.typedef_struct.v, tests/run_tests.vsh
fix #177
```c
typedef struct ImVec4 ImVec4;
struct ImVec4
{
float x, y, z, w;
};
```
https://github.com/vlang/c2v/issues/177
=> fix typedef before struct

src/c2v.v
Due to missing keywords some translated code would include v keywords as variable names causing invalid translated code. I have added all keywords listed in [the docs](https://docs.vlang.io/appendix-i-keywords.html). This also fixes my issue #191.
=> fix: update v keywords list (fix #191)

src/c2v.v
I noticed some errors related to the syntax used for function attributes.
I hope this fixes them.
=> Use up-to-date syntax for function attributes
